/**
 * This file was autogenerated by glgen (https://github.com/seshbot/glgen) on 2015-06-13
 * Command line: src/gen.py assets/gl.xml -p assets/gl-patch.xml -o ../glpp/ --includesubdir include/glpp --sourcesubdir src --namespace gles2 --force --cpp --es2only
 */

#ifndef COMMANDS__H
#define COMMANDS__H


#include "../types.h"
#include "enums.h"

namespace gles2 {
    void active_texture(texture_unit_t texture);

    void attach_shader(gl::uint_t program, gl::uint_t shader);

    void bind_attrib_location(gl::uint_t program, gl::uint_t index, const  gl::char_t * name);

    void bind_buffer(buffer_target_arb_t target, gl::uint_t buffer);

    void bind_framebuffer(framebuffer_target_t target, gl::uint_t framebuffer);

    void bind_renderbuffer(renderbuffer_target_t target, gl::uint_t renderbuffer);

    void bind_texture(texture_target_t target, gl::uint_t texture);

    void blend_color(gl::float_t red, gl::float_t green, gl::float_t blue, gl::float_t alpha);

    void blend_equation(blend_equation_mode_t mode);

    void blend_equation_separate(blend_equation_mode_ext_t modeRGB, blend_equation_mode_ext_t modeAlpha);

    void blend_func(blending_factor_src_t sfactor, blending_factor_dest_t dfactor);

    void blend_func_separate(blend_func_separate_parameter_ext_t sfactorRGB, blend_func_separate_parameter_ext_t dfactorRGB, blend_func_separate_parameter_ext_t sfactorAlpha, blend_func_separate_parameter_ext_t dfactorAlpha);

    void buffer_data(buffer_target_arb_t target, gl::sizeiptr_t size, const  void * data, buffer_usage_arb_t usage);

    void buffer_sub_data(buffer_target_arb_t target, gl::intptr_t offset, gl::sizeiptr_t size, const  void * data);

    framebuffer_status_t check_framebuffer_status(framebuffer_target_t target);

    void clear(gl::bitmask<clear_buffer_flags_t> mask);

    void clear_color(gl::float_t red, gl::float_t green, gl::float_t blue, gl::float_t alpha);

    void clear_depthf(gl::float_t d);

    void clear_stencil(gl::int_t s);

    void color_mask(gl::boolean_t red, gl::boolean_t green, gl::boolean_t blue, gl::boolean_t alpha);

    void compile_shader(gl::uint_t shader);

    void compressed_tex_image_2d(texture_target_t target, gl::int_t level, gl::enum_t internalformat, gl::sizei_t width, gl::sizei_t height, gl::int_t border, gl::sizei_t imageSize, const  void * data);

    void compressed_tex_sub_image_2d(texture_target_t target, gl::int_t level, gl::int_t xoffset, gl::int_t yoffset, gl::sizei_t width, gl::sizei_t height, pixel_format_t format, gl::sizei_t imageSize, const  void * data);

    void copy_tex_image_2d(texture_target_t target, gl::int_t level, gl::enum_t internalformat, gl::int_t x, gl::int_t y, gl::sizei_t width, gl::sizei_t height, gl::int_t border);

    void copy_tex_sub_image_2d(texture_target_t target, gl::int_t level, gl::int_t xoffset, gl::int_t yoffset, gl::int_t x, gl::int_t y, gl::sizei_t width, gl::sizei_t height);

    gl::uint_t create_program();

    gl::uint_t create_shader(shader_type_t type);

    void cull_face(cull_face_mode_t mode);

    void delete_buffers(gl::sizei_t n, const  gl::uint_t * buffers);

    void delete_framebuffers(gl::sizei_t n, const  gl::uint_t * framebuffers);

    void delete_program(gl::uint_t program);

    void delete_renderbuffers(gl::sizei_t n, const  gl::uint_t * renderbuffers);

    void delete_shader(gl::uint_t shader);

    void delete_textures(gl::sizei_t n, const  gl::uint_t * textures);

    void depth_func(depth_function_t func);

    void depth_mask(gl::boolean_t flag);

    void depth_rangef(gl::float_t n, gl::float_t f);

    void detach_shader(gl::uint_t program, gl::uint_t shader);

    void disable(enable_cap_t cap);

    void disable_vertex_attrib_array(gl::uint_t index);

    void draw_arrays(primitive_type_t mode, gl::int_t first, gl::sizei_t count);

    void draw_elements(primitive_type_t mode, gl::sizei_t count, draw_elements_type_t type, const  void * indices);

    void enable(enable_cap_t cap);

    void enable_vertex_attrib_array(gl::uint_t index);

    void finish();

    void flush();

    void framebuffer_renderbuffer(framebuffer_target_t target, framebuffer_attachment_t attachment, renderbuffer_target_t renderbuffertarget, gl::uint_t renderbuffer);

    void framebuffer_texture_2d(framebuffer_target_t target, framebuffer_attachment_t attachment, framebuffer_texture_target_t textarget, gl::uint_t texture, gl::int_t level);

    void front_face(front_face_direction_t mode);

    void gen_buffers(gl::sizei_t n, gl::uint_t * buffers);

    void gen_framebuffers(gl::sizei_t n, gl::uint_t * framebuffers);

    void gen_renderbuffers(gl::sizei_t n, gl::uint_t * renderbuffers);

    void gen_textures(gl::sizei_t n, gl::uint_t * textures);

    void generate_mipmap(mipmap_target_t target);

    void get_active_attrib(gl::uint_t program, gl::uint_t index, gl::sizei_t bufSize, gl::sizei_t * length, gl::int_t * size, attrib_type_t * type, gl::char_t * name);

    void get_active_uniform(gl::uint_t program, gl::uint_t index, gl::sizei_t bufSize, gl::sizei_t * length, gl::int_t * size, uniform_type_t * type, gl::char_t * name);

    void get_attached_shaders(gl::uint_t program, gl::sizei_t maxCount, gl::sizei_t * count, gl::uint_t * shaders);

    gl::int_t get_attrib_location(gl::uint_t program, const  gl::char_t * name);

    void get_booleanv(get_p_name_t pname, gl::boolean_t * data);

    void get_buffer_parameteriv(buffer_target_arb_t target, buffer_p_name_arb_t pname, gl::int_t * params);

    error_code_t get_error();

    void get_floatv(get_p_name_t pname, gl::float_t * data);

    void get_framebuffer_attachment_parameteriv(framebuffer_target_t target, framebuffer_attachment_t attachment, gl::enum_t pname, gl::int_t * params);

    void get_integerv(get_p_name_t pname, gl::int_t * data);

    void get_program_info_log(gl::uint_t program, gl::sizei_t bufSize, gl::sizei_t * length, gl::char_t * infoLog);

    void get_programiv(gl::uint_t program, get_programiv_p_name_t pname, gl::int_t * params);

    void get_renderbuffer_parameteriv(renderbuffer_target_t target, gl::enum_t pname, gl::int_t * params);

    void get_shader_info_log(gl::uint_t shader, gl::sizei_t bufSize, gl::sizei_t * length, gl::char_t * infoLog);

    void get_shader_precision_format(shader_type_t shadertype, precision_type_t precisiontype, gl::int_t * range, gl::int_t * precision);

    void get_shader_source(gl::uint_t shader, gl::sizei_t bufSize, gl::sizei_t * length, gl::char_t * source);

    void get_shaderiv(gl::uint_t shader, get_shaderiv_p_name_t pname, gl::int_t * params);

    const gl::ubyte_t * get_string(string_name_t name);

    void get_tex_parameterfv(texture_target_t target, get_texture_parameter_t pname, gl::float_t * params);

    void get_tex_parameteriv(texture_target_t target, get_texture_parameter_t pname, gl::int_t * params);

    gl::int_t get_uniform_location(gl::uint_t program, const  gl::char_t * name);

    void get_uniformfv(gl::uint_t program, gl::int_t location, gl::float_t * params);

    void get_uniformiv(gl::uint_t program, gl::int_t location, gl::int_t * params);

    void get_vertex_attrib_pointerv(gl::uint_t index, vertex_attrib_pointer_property_arb_t pname, void ** pointer);

    void get_vertex_attribfv(gl::uint_t index, vertex_attrib_property_arb_t pname, gl::float_t * params);

    void get_vertex_attribiv(gl::uint_t index, vertex_attrib_property_arb_t pname, gl::int_t * params);

    void hint(hint_target_t target, hint_mode_t mode);

    gl::boolean_t is_buffer(gl::uint_t buffer);

    gl::boolean_t is_enabled(enable_cap_t cap);

    gl::boolean_t is_framebuffer(gl::uint_t framebuffer);

    gl::boolean_t is_program(gl::uint_t program);

    gl::boolean_t is_renderbuffer(gl::uint_t renderbuffer);

    gl::boolean_t is_shader(gl::uint_t shader);

    gl::boolean_t is_texture(gl::uint_t texture);

    void line_width(gl::float_t width);

    void link_program(gl::uint_t program);

    void pixel_storei(pixel_store_parameter_t pname, gl::int_t param);

    void polygon_offset(gl::float_t factor, gl::float_t units);

    void read_pixels(gl::int_t x, gl::int_t y, gl::sizei_t width, gl::sizei_t height, pixel_format_t format, pixel_type_t type, void * pixels);

    void release_shader_compiler();

    void renderbuffer_storage(renderbuffer_target_t target, internal_format_t internalformat, gl::sizei_t width, gl::sizei_t height);

    void sample_coverage(gl::float_t value, gl::boolean_t invert);

    void scissor(gl::int_t x, gl::int_t y, gl::sizei_t width, gl::sizei_t height);

    void shader_binary(gl::sizei_t count, const  gl::uint_t * shaders, gl::enum_t binaryformat, const  void * binary, gl::sizei_t length);

    void shader_source(gl::uint_t shader, gl::sizei_t count, const  gl::char_t ** string, const  gl::int_t * length);

    void stencil_func(stencil_function_t func, gl::int_t ref, gl::uint_t mask);

    void stencil_func_separate(stencil_face_direction_t face, stencil_function_t func, gl::int_t ref, gl::uint_t mask);

    void stencil_mask(gl::uint_t mask);

    void stencil_mask_separate(stencil_face_direction_t face, gl::uint_t mask);

    void stencil_op(stencil_op_t fail, stencil_op_t zfail, stencil_op_t zpass);

    void stencil_op_separate(stencil_face_direction_t face, stencil_op_t sfail, stencil_op_t dpfail, stencil_op_t dppass);

    void tex_image_2d(texture_image_target_t target, gl::int_t level, texture_component_count_t internalformat, gl::sizei_t width, gl::sizei_t height, gl::int_t border, pixel_format_t format, pixel_type_t type, const  void * pixels);

    void tex_parameterf(texture_target_t target, texture_parameter_name_t pname, gl::float_t param);

    void tex_parameterfv(texture_target_t target, texture_parameter_name_t pname, const  gl::float_t * params);

    void tex_parameteri(texture_target_t target, texture_parameter_name_t pname, gl::int_t param);

    void tex_parameteriv(texture_target_t target, texture_parameter_name_t pname, const  gl::int_t * params);

    void tex_sub_image_2d(texture_target_t target, gl::int_t level, gl::int_t xoffset, gl::int_t yoffset, gl::sizei_t width, gl::sizei_t height, pixel_format_t format, pixel_type_t type, const  void * pixels);

    void uniform_1f(gl::int_t location, gl::float_t v0);

    void uniform_1fv(gl::int_t location, gl::sizei_t count, const  gl::float_t * value);

    void uniform_1i(gl::int_t location, gl::int_t v0);

    void uniform_1iv(gl::int_t location, gl::sizei_t count, const  gl::int_t * value);

    void uniform_2f(gl::int_t location, gl::float_t v0, gl::float_t v1);

    void uniform_2fv(gl::int_t location, gl::sizei_t count, const  gl::float_t * value);

    void uniform_2i(gl::int_t location, gl::int_t v0, gl::int_t v1);

    void uniform_2iv(gl::int_t location, gl::sizei_t count, const  gl::int_t * value);

    void uniform_3f(gl::int_t location, gl::float_t v0, gl::float_t v1, gl::float_t v2);

    void uniform_3fv(gl::int_t location, gl::sizei_t count, const  gl::float_t * value);

    void uniform_3i(gl::int_t location, gl::int_t v0, gl::int_t v1, gl::int_t v2);

    void uniform_3iv(gl::int_t location, gl::sizei_t count, const  gl::int_t * value);

    void uniform_4f(gl::int_t location, gl::float_t v0, gl::float_t v1, gl::float_t v2, gl::float_t v3);

    void uniform_4fv(gl::int_t location, gl::sizei_t count, const  gl::float_t * value);

    void uniform_4i(gl::int_t location, gl::int_t v0, gl::int_t v1, gl::int_t v2, gl::int_t v3);

    void uniform_4iv(gl::int_t location, gl::sizei_t count, const  gl::int_t * value);

    void uniform_matrix_2fv(gl::int_t location, gl::sizei_t count, gl::boolean_t transpose, const  gl::float_t * value);

    void uniform_matrix_3fv(gl::int_t location, gl::sizei_t count, gl::boolean_t transpose, const  gl::float_t * value);

    void uniform_matrix_4fv(gl::int_t location, gl::sizei_t count, gl::boolean_t transpose, const  gl::float_t * value);

    void use_program(gl::uint_t program);

    void validate_program(gl::uint_t program);

    void vertex_attrib_1f(gl::uint_t index, gl::float_t x);

    void vertex_attrib_1fv(gl::uint_t index, const  gl::float_t * v);

    void vertex_attrib_2f(gl::uint_t index, gl::float_t x, gl::float_t y);

    void vertex_attrib_2fv(gl::uint_t index, const  gl::float_t * v);

    void vertex_attrib_3f(gl::uint_t index, gl::float_t x, gl::float_t y, gl::float_t z);

    void vertex_attrib_3fv(gl::uint_t index, const  gl::float_t * v);

    void vertex_attrib_4f(gl::uint_t index, gl::float_t x, gl::float_t y, gl::float_t z, gl::float_t w);

    void vertex_attrib_4fv(gl::uint_t index, const  gl::float_t * v);

    void vertex_attrib_pointer(gl::uint_t index, gl::int_t size, vertex_attrib_pointer_type_t type, gl::boolean_t normalized, gl::sizei_t stride, const  void * pointer);

    void viewport(gl::int_t x, gl::int_t y, gl::sizei_t width, gl::sizei_t height);

} // namespace gles2

#endif // #ifndef COMMANDS__H
